production:
  username: 'satoyama'
  password: 'satoyama'
  dbname: 'satoyama_prod'
  dbhost: 'localhost'
development:
  username: 'halfdan'
  password: 'halfdan'
  dbname: 'satoyama_dev'
  dbhost: 'localhost'
test:
  username: 'satoyama'
  password: 'satoyama'
  dbname: 'satoyama_test'
  dbhost: 'localhost'