from argparse import ArgumentParser, Namespace
import requests
verbs = {
	'create' : 'created',
	'destroy': 'destroyed'
}

class Konohana(object):

	@classmethod
	def confirm_destroy(satoyama_type, mid, **kwargs):
		invalid_choice = True
		while invalid_choice:
			choice = raw_input('Are you sure that you want to destroy %s %s and all data it owns? [Y/n]? '%(satoyama_type, mid))
			if choice in ['Y', 'y', 'Yes', 'yes']:
				print 'Destroyed %s %s'%(satoyama_type, mid)
				return True
			elif choice in ['n', 'N', 'no', 'No']:
				return False
			else:
				print 'Please choose yes or no :)'

	@classmethod
	def send_raw_input(**args):
		requsts.post

	@classmethod
	def create_node(alias, node_type, short_address, site):

if __name__ == "__main__":
	parser = ArgumentParser()

	parser.add_argument('-y', action='store_true', help='If specified, Konohana will not ask for confirmation when destroying Satoyama entities.')
	subparsers = parser.add_subparsers(help='sub-command help', dest = 'action')

	parser_create_node = subparsers.add_parser('create-node', help='Create a site or node')
	parser_create_node.add_argument('name', type = str, help = 'The name of the node (e.g. "ricefield_small_waterlevel")')
	parser_create_node.add_argument('--node_type', '-t', choices = ('ricefield', 'herbs'))
	parser_create_node.add_argument('--short_address', '-a', type = int, help = 'The Chibi short adress of the node')
	parser_create_node.add_argument('--site', '-s', type = int, help = 'The id of the site that the node belongs to', required = False)

	parser_destroy_node = subparsers.add_parser('destroy-node', help='Destroy a node')
	parser_destroy_node.add_argument('id', type = int, help = 'The id of the node you want to destroy')
	parser_destroy_node.add_argument('--erase_data', '-E', action = 'store_true', help = 'Set this flag to erase all sensor data generated by sensors in the node')

	parser_create_site = subparsers.add_parser('create-site', help='create a site')
	parser_create_site.add_argument('name', type = str, help = 'The name of the site (e.g. "Hackerfarm")')

	parser_destroy_site = subparsers.add_parser('destroy-site', help='Destroy a site')
	parser_destroy_site.add_argument('id', type = int, help = 'The id of the node you want to destroy')
	parser_destroy_site.add_argument('--erase_data', '-E', action = 'store_true', help = 'Set this flag to erase all sensor data generated by sensors in the node')

	args = parser.parse_args()	
	action, model = args.action.split('-')
	print action, model
	print vars(args)
