"""empty message

Revision ID: 1df2cc880b08
Revises: 7703c5acbc6
Create Date: 2015-01-08 15:55:05.348154

"""

# revision identifiers, used by Alembic.
revision = '1df2cc880b08'
down_revision = '7703c5acbc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
