"""empty message

Revision ID: 293f3aed8fdf
Revises: ffc6d6493b7
Create Date: 2014-12-30 15:35:34.928724

"""

# revision identifiers, used by Alembic.
revision = '293f3aed8fdf'
down_revision = 'ffc6d6493b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('short_address', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'nodes', ['short_address'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes')
    op.drop_column('nodes', 'short_address')
    ### end Alembic commands ###
