"""empty message

Revision ID: 2dbb6454846e
Revises: 4f62c39ed5e1
Create Date: 2015-02-18 16:54:12.032143

"""

# revision identifiers, used by Alembic.
revision = '2dbb6454846e'
down_revision = '4f62c39ed5e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
