"""Adds node_type table

Revision ID: 4f62c39ed5e1
Revises: 1df2cc880b08
Create Date: 2015-02-18 16:48:36.165183

"""

# revision identifiers, used by Alembic.
revision = '4f62c39ed5e1'
down_revision = '1df2cc880b08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table(u'nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nodetype_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'nodes', schema=None) as batch_op:
        batch_op.drop_column('nodetype_id')

    op.drop_table('nodetypes')
    ### end Alembic commands ###
