"""empty message

Revision ID: 7390a8ee859
Revises: None
Create Date: 2014-10-31 15:53:48.592937

"""

# revision identifiers, used by Alembic.
revision = '7390a8ee859'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('networks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.INTEGER(), server_default="nextval('networks_id_seq'::regclass)", nullable=False),
    sa.Column('alias', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'networks_pkey')
    )
    ### end Alembic commands ###
